<?php $this->getChildHtml('toolbar');

$columns = $this->getColumns();
$collection = $this->getCollection()->getData();
?>

<div class="d-flex justify-content-end m-3 mx-4 gap-3">
    <a href="<?php echo $this->getUrl("*/*/exportCsv") ?>" class="add-btn btn btn-success">Download Csv</a>
    <a href="<?php echo $this->getUrl("*/*/new") ?>" class="add-btn btn btn-success">Add Category</a>
</div>
<div class="table-container">
    <table class="table table-bordered table-striped text-center">
        <thead class="table-dark">
            <tr class="text-center">
                <?php foreach ($columns as $column): ?>
                    <th><?php echo $column->getData()['label']; ?></th>
                <?php endforeach; ?>
            </tr>
        </thead>
        <tbody>
            <tr>
                <?php foreach ($columns as $key => $column): ?>
                    <td><?php echo $column->getFilter()->rendor() ?></td>
                <?php endforeach; ?>
            </tr>
            <?php foreach ($collection as $data): ?>
                <tr>
                    <?php foreach ($columns as $key => $column): ?>
                        <td>
                            <?php
                               echo $column->setRoW($data->getData())->rendor();
                            ?>
                        </td>
                    <?php endforeach ?>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>