<nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Admin Panel</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" href="<?php echo $this->getUrl("admin/dashboard/list")?>">dashboard</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?php echo $this->getUrl("admin/product_index/list")?>">Products</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?php echo $this->getUrl("admin/category/list")?>">Categories</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?php echo $this->getUrl("admin/order/list")?>">Orders</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Users</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link btn btn-danger text-white px-3" href="#">Logout</a>
                </li>
            </ul>
        </div>
    </div>
</nav>