
<div class="container my-4">
    <div class="row">

        <div class="col-md-12">
            <?php $this->getChildHtml('customer_info'); ?>
            <?php $this->getChildHtml('customer_address'); ?>

        </div>
    </div>
</div>

<script>
    document.getElementById('addAddressBtn').addEventListener('click', function() {
        document.getElementById('addAddressForm').style.display = 'block';
        this.style.display = 'none';
    });

    document.getElementById('cancelAddressBtn').addEventListener('click', function() {
        document.getElementById('addAddressForm').style.display = 'none';
        document.getElementById('addAddressBtn').style.display = 'block';
    });
</script>