<?php $data = $this->getProducts(); 
// $data1 = $this->getProducts()[0];
// print_r($data1->getName());
?>
<div class="m-5 rounded shadow-sm bg-white">
    <h2 class="text-center mb-4" style="color: #d10063;">Product List</h2>

    <div class="d-flex justify-content-end m-2 gap-3">
        <a href="<?php echo $this->getUrl("*/*/exportCsv")?>" class="add-btn">Download Csv</a>
        <a href="<?php echo $this->getUrl("*/*/new")?>" class="add-btn">Add Product</a>
</div>
    <table class="table table-bordered table-striped">
        <thead class="table-dark text-center">
            <tr>
                <th>Product ID</th>
                <th>Name</th>
                <th>SKU</th>
                <th>Price (₹)</th>
                <th>Stock Quantity</th>
                <th>Category</th>
                <th>color</th>
                <th>Material</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php if (!empty($data)): ?>
                <?php foreach ($data as $key => $product): ?>
                    <tr>
                        <td><?php echo htmlspecialchars($product->getProductId()); ?></td>
                        <td><?php echo htmlspecialchars($product->getName()); ?></td>
                        <td><?php echo htmlspecialchars($product->getSku()); ?></td>
                        <td><?php echo htmlspecialchars($product->getPrice()); ?></td>
                        <td><?php echo htmlspecialchars($product->getStockQuantity()); ?></td>
                        <td><?php echo htmlspecialchars($product->getCategoryId()); ?></td>
                        <td><?php echo htmlspecialchars($product->getColor()); ?></td>
                        <td><?php echo htmlspecialchars($product->getMaterial()); ?></td>
                        <td>
                            <a href="<?php echo $this->getUrl('admin/product_index/new') . '/?edit_id=' . $product->getProductId(); ?>"
                                class="btn btn-primary">Edit</a>

                            <a href="<?php echo $this->getUrl('admin/product_index/delete') . '/?delete_id=' . $product->getProductId(); ?>"
                                class="btn btn-danger"
                                onclick="return confirm('Are you sure you want to delete this item?');">
                                Delete
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="7" class="text-center">No products found.</td>
                </tr>
            <?php endif; ?>
        </tbody>
    </table>
    <?php $this->getChildHtml('toolbar')?>
</div>
